# config.yaml

# windows
#path: C:/Workspaces/AI/bot/mabinogi-mobile/ml/datasets 

# mac os
path: /Users/kojeomstudio/AI/bot/mabinogi-mobile/ml/datasets

train: images/train
val: images/val

nc: 14
names: [
  'coal_vein',
  'ui_attack',
  'ui_inventory',
  'ui_riding',
  'ui_mining',
  'ui_craft',
  'ui_compass',
  'iron_vein',
  'normal_vein',
  'tree',
  'ui_working',
  'ui_riding_out',
  'ui_felling',
  'ui_wing']