[completion]
provider = "litellm"
concurrent_request_limit = 3

  [completion.generation_config]
  model = "ollama/EEVE-Korean-Instruct-10.8B-v1.0-Q4_K_S.gguf:latest"
  temperature = 0.1
  top_p = 1
  max_tokens_to_sample = 1_024
  stream = true
  add_generation_kwargs = { }


[database]
provider = "postgres"

[embedding]
provider = "ollama"
base_model = "mxbai-embed-large"
base_dimension = 1_024
batch_size = 128
add_title_as_prefix = true
concurrent_request_limit = 2