[agent]
system_instruction_name = "my_custom_local_rag_agent"
tool_names = ["search"]

  [agent.generation_config]
  model = "ollama/EEVE-Korean-Instruct-10.8B-v1.0-Q4_K_S.gguf:latest"

[completion]
provider = "litellm"
concurrent_request_limit = 6

  [completion.generation_config]
  model = "ollama/EEVE-Korean-Instruct-10.8B-v1.0-Q4_K_S.gguf:latest"
  temperature = 0.1
  top_p = 1
  max_tokens_to_sample = 1_024
  stream = false
  add_generation_kwargs = { }

[embedding]
provider = "ollama"
base_model = "EEVE-Korean-Instruct-10.8B-v1.0-Q4_K_S.gguf:latest"
base_dimension = 1_024
batch_size = 32
add_title_as_prefix = true
concurrent_request_limit = 2

[ingestion]
provider = "unstructured_local"
strategy = "auto"
chunking_strategy = "by_title"
new_after_n_chars = 512
max_characters = 1_024
combine_under_n_chars = 128
overlap = 20

[logging]
provider = "local"
log_table = "logs"
log_info_table = "log_info"

[orchestration]
provider = "hatchet"