[agent]
system_instruction_name = "my_custom_local_rag_agent"
tool_names = ["search"]

  [agent.generation_config]
  model = "ollama/EEVE-Korean-Instruct-10.8B-v1.0-Q4_K_S.gguf:latest"

[completion]
provider = "litellm"
concurrent_request_limit = 6

  [completion.generation_config]
  model = "ollama/qEEVE-Korean-Instruct-10.8B-v1.0-Q4_K_S.gguf:latest"
  temperature = 0.1
  top_p = 1
  max_tokens_to_sample = 1_024
  stream = false
  add_generation_kwargs = { }

[embedding]
provider = "ollama"
base_model = "EEVE-Korean-Instruct-10.8B-v1.0-Q4_K_S.gguf:latest"
base_dimension = 1_024
batch_size = 32
add_title_as_prefix = true
concurrent_request_limit = 2

[ingestion]
provider = "unstructured_local"
strategy = "auto"
chunking_strategy = "by_title"
new_after_n_chars = 512
max_characters = 1_024
combine_under_n_chars = 128
overlap = 20
vision_img_model = "ollama/llama3.2-vision"
vision_pdf_model = "ollama/llama3.2-vision"

[database]
provider = "postgres"
[database.kg_creation_settings]
    kg_entity_description_prompt = "graphrag_entity_description"
    kg_triples_extraction_prompt = "graphrag_triples_extraction_few_shot"
    entity_types = [] # if empty, all entities are extracted
    relation_types = [] # if empty, all relations are extracted
    fragment_merge_count = 4 # number of fragments to merge into a single extraction
    max_knowledge_triples = 100
    max_description_input_length = 65536
    generation_config = { model = "ollama/EEVE-Korean-Instruct-10.8B-v1.0-Q4_K_S.gguf:latest" } # and other params, model used for triplet extraction

  [database.kg_entity_deduplication_settings]
    kg_entity_deduplication_type = "by_name"
    kg_entity_deduplication_prompt = "graphrag_entity_deduplication"
    max_description_input_length = 65536
    generation_config = { model = "ollama/EEVE-Korean-Instruct-10.8B-v1.0-Q4_K_S.gguf:latest" } # and other params, model used for deduplication

  [database.kg_enrichment_settings]
    community_reports_prompt = "graphrag_community_reports"
    max_summary_input_length = 65536
    generation_config = { model = "ollama/EEVE-Korean-Instruct-10.8B-v1.0-Q4_K_S.gguf:latest" } # and other params, model used for node description and graph clustering
    leiden_params = {}

  [database.kg_search_settings]
    entities_level = "document" # set to collection if you've run deduplication
    map_system_prompt = "graphrag_map_system"
    reduce_system_prompt = "graphrag_reduce_system"
    generation_config = { model = "ollama/EEVE-Korean-Instruct-10.8B-v1.0-Q4_K_S.gguf:latest" }

[logging]
provider = "local"
log_table = "logs"
log_info_table = "log_info"

[orchestration]
provider = "hatchet"