#
# 기존 r2r.toml을 적절하게 수정한 버전.
# - 디폴트 r2r.toml은 r2r-original.toml로 이름 수정.
# - 모든 섹션에 대한 기록이 되어 있는 파일은 full-r2r.toml로 버전관리.
#

[app]
# LLM used for internal operations, like deriving conversation names
fast_llm = "ollama/qwen2.5-coder:latest"

# LLM used for user-facing output, like RAG replies
quality_llm = "ollama/qwen2.5-coder:latest"

# LLM used for ingesting visual inputs
vlm = "ollama/llama3.2-vision" # TODO - Replace with viable candidate

# LLM used for transcription
audio_lm = "ollama/qwen2.5-coder:latest" # TODO - Replace with viable candidate

[embedding]
provider = "ollama"
base_model = "mxbai-embed-large"
base_dimension = 1_024
batch_size = 128
add_title_as_prefix = true
concurrent_request_limit = 2

[completion_embedding]
provider = "ollama"
base_model = "mxbai-embed-large"
base_dimension = 1_024
batch_size = 128
add_title_as_prefix = true
concurrent_request_limit = 2

[agent]
agent_static_prompt = "static_rag_agent"
agent_dynamic_prompt = "dynamic_rag_agent"
tools = ["content", "local_search"]
tool_names=["content", "local_search"]

  [agent.generation_config]
  model = "ollama/qwen2.5-coder:latest"

[completion]
provider = "litellm"
concurrent_request_limit = 1

  [completion.generation_config]
  temperature = 0.1
  top_p = 1
  max_tokens_to_sample = 1_024
  stream = false

[ingestion]
chunks_for_document_summary = 16
document_summary_model = "ollama/qwen2.5-coder:latest"
automatic_extraction = true

[database]
provider = "postgres"
default_collection_name = "Default"
default_collection_description = "Your default collection."
collection_summary_prompt = "collection_summary"

  [database.graph_creation_settings]
    graph_entity_description_prompt = "graphrag_entity_description"
    entity_types = [] # if empty, all entities are extracted
    relation_types = [] # if empty, all relations are extracted
    fragment_merge_count = 4 # number of fragments to merge into a single extraction
    max_knowledge_relationships = 100
    max_description_input_length = 65536
    generation_config = { model = "ollama/qwen2.5-coder:latest" } # and other params, model used for relationshipt extraction
    automatic_deduplication = false

  [database.graph_enrichment_settings]
    community_reports_prompt = "graphrag_community_reports"
    max_summary_input_length = 65536
    generation_config = { model = "ollama/qwen2.5-coder:latest" } # and other params, model used for node description and graph clustering
    leiden_params = {}

  [database.graph_search_settings]
    generation_config = { model = "ollama/qwen2.5-coder:latest" }


[auth]
provider = "r2r"
access_token_lifetime_in_minutes = 60
refresh_token_lifetime_in_days = 7
require_authentication = true
require_email_verification = false
default_admin_email = "admin@example.com"
default_admin_password = "change_me_immediately"

[crypto]
provider = "bcrypt"

[logging]
provider = "r2r"
log_table = "logs"
log_info_table = "log_info"

[orchestration]
provider = "simple"

[prompt]
provider = "r2r"

[email]
provider = "console_mock"