# Nexus Repository OSS 3.x (공식)
FROM sonatype/nexus3:latest

# JVM 힙, GC 로그 등 커스터마이즈가 필요하면 환경변수 또는 JVM_OPTS로 조정 가능
# 예) ENV INSTALL4J_ADD_VM_PARAMS="-Xms1200m -Xmx1200m -XX:+UseG1GC -Djava.util.prefs.userRoot=/nexus-data/javaprefs"

# 기본 ENTRYPOINT/CMD는 베이스 이미지 그대로 사용
